name: Connect Org Workflow
run-name: Connect Org
on: workflow_dispatch
env: IT
jobs:
  show-secret:
    name: Show secret
    runs-on: ubuntu-22.04
    steps:
      -  name: print env secret
         env:
            SECRET_ENV: ${{ secrets.TEST_SECRET }}
         run: echo "$SECRET_ENV"