name: Connect Org 2 Workflow
run-name: Connect Org
on: workflow_dispatch
environment: IT
jobs:
  show-secret:
    name: Show secret
    runs-on: ubuntu-22.04
    steps:
      -  name: print env secret
         env:
            TOKEN: ${{ secrets.TEST_SECRET }}
         run: echo "token env $TOKEN"