name: Run validation workflow
run-name: Validate, test and deploy
on: workflow_dispatch
jobs:
  run-validation:
    name: Run Validation job
    runs-on: ubuntu-22.04
    steps:
      -  name: Download files from repository
         uses: actions/checkout@v4
      -  name: Install SF CLI
         run: npm install sf
      -  name: Authenticate on DevHub
         run: sf org list